In [2]:
import pandas as pd
from pathlib import Path
import ast

In [3]:
syllable_frequencies = pd.read_csv('/home/lillianchang/Documents/MOUS_hierarchical-representations/tables/guslatho_MOUS_word_syllable_frequencies.csv',index_col=0)
syllable_frequencies.head()

,Word,n_syllables,Log10_Syllable_FREQcounts,Syllable_Zipfs,Min_Log10_FreqCount,Min_Syll_Zipf
0,ik,1,"(6.241737438532683,)","(7.468668823067624,)",6.241737,7.468669
1,je,1,"(6.249430979053402,)","(7.476362363588343,)",6.249431,7.476362
2,het,1,"(6.032457179694622,)","(7.259388564229563,)",6.032457,7.259389
3,de,1,"(6.234172950952972,)","(7.461104335487914,)",6.234173,7.461104
4,dat,1,"(6.012697215956926,)","(7.239628600491868,)",6.012697,7.239629

In [4]:
print(type(syllable_frequencies['Syllable_Zipfs'][0]))

<class 'str'>

In [5]:
syllable_frequencies['First_syllable_zipf'] = syllable_frequencies['Syllable_Zipfs'].apply(ast.literal_eval)
syllable_frequencies['First_syllable_zipf'] = syllable_frequencies['First_syllable_zipf'].str[0]
syllable_frequencies.head(200)

,Word,n_syllables,Log10_Syllable_FREQcounts,Syllable_Zipfs,Min_Log10_FreqCount,Min_Syll_Zipf,First_syllable_zipf
0,ik,1,"(6.241737438532683,)","(7.468668823067624,)",6.241737,7.468669,7.468669
1,je,1,"(6.249430979053402,)","(7.476362363588343,)",6.249431,7.476362,7.476362
2,het,1,"(6.032457179694622,)","(7.259388564229563,)",6.032457,7.259389,7.259389
3,de,1,"(6.234172950952972,)","(7.461104335487914,)",6.234173,7.461104,7.461104
4,dat,1,"(6.012697215956926,)","(7.239628600491868,)",6.012697,7.239629,7.239629
...,...,...,...,...,...,...,...
195,na,1,"(5.202455621138131,)","(6.429387005673073,)",5.202456,6.429387,6.429387
196,graag,1,"(4.415490852171469,)","(5.64242223670641,)",4.415491,5.642422,5.642422
197,toe,1,"(4.799698866883532,)","(6.026630251418473,)",4.799699,6.026630,6.026630
198,helpen,2,"(4.5310827620341625, 5.250193036344548)","(5.758014146569104, 6.477124420879489)",4.531083,5.758014,5.758014
199,zegt,1,"(4.404799518857654,)","(5.6317309033925955,)",4.404800,5.631731,5.631731

In [6]:
export = syllable_frequencies[['Word','n_syllables','Min_Syll_Zipf','First_syllable_zipf']]
export.to_csv('/home/lillianchang/Documents/MOUS_hierarchical-representations/tables/first_syllable_frequency.csv')

In [7]:
export

            Word  n_syllables  Min_Syll_Zipf  First_syllable_zipf
0             ik            1       7.468669             7.468669
1             je            1       7.476362             7.476362
2            het            1       7.259389             7.259389
3             de            1       7.461104             7.461104
4            dat            1       7.239629             7.239629
...          ...          ...            ...                  ...
278056    aagghh            1       1.527961             1.527961
278057  aagezien            3       2.745445             2.745445
278058       aaf            1       1.527961             1.527961
278059    aada's            0            NaN                  NaN
278060  aachener            3       2.745445             2.745445

[277954 rows x 4 columns]

In [13]:
mous_bigrams = pd.read_csv("/home/lillianchang/Documents/MOUS_hierarchical-representations/tables/mous_words_syllable_bigram_frequencies.csv")

merged = mous_bigrams.merge(
    syllable_frequencies[["Word", "n_syllables", "Min_Syll_Zipf", "First_syllable_zipf"]],
    on="Word",
    how="left",
)

merged.to_csv('/home/lillianchang/Documents/MOUS_hierarchical-representations/tables/mous_words_first_vs_min_syllable.csv')
merged

,Word,IPA,Syllables,Min_Freq_Count,Max_Freq_Count,Mean_Freq_Count,Bigrams,Bigram Occurrence Counts,Zipf,FREQcount,Lg10WF,n_syllables,Min_Syll_Zipf,First_syllable_zipf
0,toen,tˈun,tun,177.0,177.0,1.770000e+02,"['to', 'oe', 'en']","[2236591.0, 837795.0, 8542439.0]",6.032333,47514.0,4.676822,1.0,5.907385,5.907385
1,de,dˈə,də,208410.0,208410.0,2.084100e+05,['de'],[2559661.0],7.381291,1061177.0,6.025788,1.0,7.461104,7.461104
2,barkeeper,bˈɑrkeːpər,bɑr - keː - pər,1201.0,22550.0,1.399933e+04,"['ba', 'ar', 'rk', 'ke', 'ee', 'ep', 'pe', 'er']","[584273.0, 1754491.0, 2174749.0, 3143026.0, 94...",3.622674,184.0,2.264818,3.0,4.404756,5.201443
3,die,dˈi,di,441857.0,441857.0,4.418570e+05,"['di', 'ie']","[1050254.0, 2076673.0]",6.853871,315041.0,5.498367,1.0,6.754686,6.754686
4,irritante,ˌɪɾritˈɑntə,ɪɾ - ri - tɑn - tə,8.0,995799.0,2.623075e+05,"['ir', 'rr', 'ri', 'it', 'ta', 'an', 'nt', 'te']","[2884214.0, 200692.0, 1787712.0, 333345.0, 892...",3.284921,84.0,1.924279,4.0,4.273036,4.273036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1937,blije,blˈɛɪə,blɛɪ - ə,1796.0,2281166.0,1.141481e+06,"['bl', 'li', 'ij', 'je']","[152155.0, 3369152.0, 1639122.0, 913788.0]",3.485836,134.0,2.127105,2.0,5.800800,5.800800
1938,jongeren,jˈɔŋərən,jɔŋ - ə - rən,6659.0,2281166.0,7.780040e+05,"['jo', 'on', 'ng', 'ge', 'er', 're', 'en']","[866375.0, 2451854.0, 2927082.0, 3692145.0, 67...",3.965097,406.0,2.608526,3.0,5.895532,5.895532
1939,intens,ˈɪntəns,ɪn - təns,575.0,214096.0,1.073355e+05,"['in', 'nt', 'te', 'en', 'ns']","[2264626.0, 1477178.0, 3522714.0, 8542439.0, 6...",3.778748,264.0,2.421604,2.0,4.149657,6.931582
1940,plezier,pleːzˈir,pleː - zir,1573.0,6109.0,3.841000e+03,"['pl', 'le', 'ez', 'zi', 'ie', 'er']","[97171.0, 4397946.0, 100963.0, 123482.0, 20766...",5.093966,5475.0,3.738384,2.0,5.015453,5.180739
1941,woonplaats,ʋˈoːnplˌaːts,ʋoːn - plaːts,2198.0,14293.0,8.245500e+03,"['wo', 'oo', 'on', 'np', 'pl', 'la', 'aa', 'at...","[933919.0, 3901750.0, 2451854.0, 16967.0, 9717...",3.241993,76.0,1.880814,2.0,5.358165,5.947008

In [16]:
source = Path('/mnt/MOUSnew/SynologyDrive/source/SynologyDrive')

for subject in source.rglob('sub-A*'):
    if subject.is_dir():
        # Read the transcription file
        transcription = pd.read_csv(str(subject / 'func' / f'{subject.name}_transcription.csv'))
        
        # Rename the column for consistency
        transcription.rename(columns={'Transcription': 'Word'}, inplace=True)
        transcription['Word'] = transcription['Word'].apply(lambda x: str(x).lower())
        # Merge transcription with syllable_table on the Word column
        transcription = transcription.merge(
            export[['Word', 'n_syllables', 'Min_Syll_Zipf','First_syllable_zipf']],
            on='Word',
            how='left'
        )
        
        # Rename columns for clarity
        transcription.rename(
            columns={
                'Min_Syll_Zipf': 'MinSyllZipf'
            },
            inplace=True
        )
        outpath = subject / 'func' / f'{subject.name}_first_syllable_frequency.csv'
        outpath2 = subject / 'func' / f'{subject.name}_first_syllable_frequency_restricted.csv'
        transcription.to_csv(str(outpath))
        transcription_init_not_min = transcription[transcription['First_syllable_zipf'] != transcription['MinSyllZipf']]
        transcription_init_not_min.to_csv(str(outpath2))

In [15]:
data = pd.read_csv(outpath)
data.head()

,Unnamed: 0,TextGrid,Word,AlignOnset,AlignOffset,OnsetPhoneme,OffsetPhoneme,Duration,n_syllables,MinSyllZipf,First_syllable_zipf
0,0,870,toekomst,10.16,0.52,t,s,0.52,2.0,5.167547,6.026630
1,1,870,bol,10.80,1.07,b,l,0.43,1.0,4.445204,4.445204
2,2,870,met,11.38,1.56,m,t,0.34,1.0,6.702507,6.702507
3,3,870,glazen,11.93,2.38,x,@,0.61,2.0,4.376150,4.376150
4,4,870,waarzegster,12.72,3.35,w,r,0.79,3.0,5.663348,6.695605